// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package org.example.grpc;

public final class HelloServiceOuterClass {
  private HelloServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_grpc_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_grpc_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_grpc_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_grpc_MessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HelloService.proto\022\020org.example.grpc\";" +
      "\n\016MessageRequest\022\n\n\002id\030\001 \001(\005\022\017\n\007message\030" +
      "\002 \001(\t\022\014\n\004date\030\003 \001(\t\"&\n\017MessageResponse\022\023" +
      "\n\013msgResponse\030\001 \001(\t2\\\n\014HelloService\022L\n\005h" +
      "ello\022 .org.example.grpc.MessageRequest\032!" +
      ".org.example.grpc.MessageResponseB\002P\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_grpc_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_grpc_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_grpc_MessageRequest_descriptor,
        new java.lang.String[] { "Id", "Message", "Date", });
    internal_static_org_example_grpc_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_example_grpc_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_grpc_MessageResponse_descriptor,
        new java.lang.String[] { "MsgResponse", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
