// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package org.example.grpc;

public interface MessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.grpc.MessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string msgResponse = 1;</code>
   * @return The msgResponse.
   */
  java.lang.String getMsgResponse();
  /**
   * <code>string msgResponse = 1;</code>
   * @return The bytes for msgResponse.
   */
  com.google.protobuf.ByteString
      getMsgResponseBytes();
}
