// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HelloService.proto

package main.proto.org.example.grpc;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.example.grpc.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string date = 3;</code>
   * @return The date.
   */
  String getDate();
  /**
   * <code>string date = 3;</code>
   * @return The bytes for date.
   */
  com.google.protobuf.ByteString
      getDateBytes();
}
